# Module outputs go here.
# Always include descriptions as they will populate
# autogenerated documentation.

output "pet_name" {
  description = <<-EOT
      A random pet name.
    EOT
  value       = random_pet.this.id
}