# Top level variables for the module go here.
# Always include descriptions as they will populate
# autogenerated documentation.

variable "unused" {
  type        = string
  description = <<-EOT
      This variable is not used.
    EOT
  default     = null
}